// Suite: derived artifact ownership
// Invariant: every path in the Makefile's derived scan resolves to exactly one validated ownership record and truthful remediation.
// Boundary IN: DERIVED_DIGEST_PATHS, ownership YAML, read-only path resolution, and remediation diagnostics.
// Boundary OUT: executing dedicated commands and widening BASELINE_DIGEST_STEPS.

package baseline

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"testing/fstest"
)

func TestDerivedOwnershipIsExhaustive(t *testing.T) {
	t.Parallel()

	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}
	if len(resolved) == 0 {
		t.Fatal("derived scan resolved no paths")
	}
}

func TestDerivedOwnershipRejectsUnclassifiedArtifact(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/unclassified.txt": &fstest.MapFile{Data: []byte("unclassified\n")},
	}
	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "zero ownership records") {
		t.Fatalf("unclassified artifact error = %v, want zero ownership records", err)
	}
}

func TestDerivedOwnershipRejectsMultipleRecords(t *testing.T) {
	t.Parallel()

	record := []byte("owner: sanctioned\nreason: fixture\n")
	fixture := fstest.MapFS{
		"derived/_ownership.yml":  &fstest.MapFile{Data: record},
		"derived/_ownership.yaml": &fstest.MapFile{Data: record},
		"derived/artifact.txt":    &fstest.MapFile{Data: []byte("artifact\n")},
	}
	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "more than one ownership record") {
		t.Fatalf("ambiguous ownership error = %v, want more than one ownership record", err)
	}
}

func TestDerivedOwnershipValidatesRecords(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		record    string
		wantError string
	}{
		{
			name:   "sanctioned with reason",
			record: "owner: sanctioned\nreason: regenerated by the sanctioned command\n",
		},
		{
			name:   "frozen with reason",
			record: "owner: frozen\nreason: intentionally regenerated by nothing\n",
		},
		{
			name: "dedicated with command",
			record: "owner: dedicated\n" +
				"command: go test ./internal/baseline -run TestFixture\n" +
				"reason: uses a dedicated regeneration step\n",
		},
		{
			name:      "unknown owner",
			record:    "owner: inferred\nreason: invalid owner\n",
			wantError: "is not sanctioned, dedicated, or frozen",
		},
		{
			name:      "missing reason",
			record:    "owner: sanctioned\n",
			wantError: "reason is required",
		},
		{
			name:      "dedicated missing command",
			record:    "owner: dedicated\nreason: missing exact invocation\n",
			wantError: "command is required for dedicated ownership",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			fixture := fstest.MapFS{
				"derived/_ownership.yml": &fstest.MapFile{Data: []byte(test.record)},
				"derived/artifact.txt":   &fstest.MapFile{Data: []byte("artifact\n")},
			}
			_, err := validateDerivedOwnership(fixture, []string{"derived"})
			if test.wantError == "" {
				if err != nil {
					t.Fatal(err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), test.wantError) {
				t.Fatalf("validation error = %v, want %q", err, test.wantError)
			}
		})
	}
}

func TestDerivedOwnershipRemediationDiagnostics(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		scanRoot   string
		artifact   string
		recordPath string
		owner      derivedOwnershipOwner
	}{
		{
			name:       "sanctioned setup",
			scanRoot:   "assets/setups",
			artifact:   "assets/setups/go-cli.json",
			recordPath: "assets/setups/_ownership.yml",
			owner:      derivedOwnerSanctioned,
		},
		{
			name:       "dedicated plan characterization",
			scanRoot:   "testdata",
			artifact:   "testdata/plan-characterization/clean-adoption.golden.json",
			recordPath: "testdata/plan-characterization/_ownership.yml",
			owner:      derivedOwnerDedicated,
		},
		{
			name:       "frozen parity corpus",
			scanRoot:   "testdata",
			artifact:   "testdata/parity-corpus/v1/matrix.json",
			recordPath: "testdata/parity-corpus/_ownership.yml",
			owner:      derivedOwnerFrozen,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			record, err := readDerivedOwnershipRecord(os.DirFS("."), test.recordPath)
			if err != nil {
				t.Fatal(err)
			}
			if record.Owner != test.owner {
				t.Fatalf("ownership record %q owner = %q, want %q", test.recordPath, record.Owner, test.owner)
			}
			got, err := derivedArtifactRemediation(os.DirFS("."), test.scanRoot, test.artifact)
			if err != nil {
				t.Fatal(err)
			}

			switch test.owner {
			case derivedOwnerSanctioned:
				if got != baselineDigestRegenerationHint {
					t.Fatalf("sanctioned remediation = %q, want unchanged %q", got, baselineDigestRegenerationHint)
				}
			case derivedOwnerDedicated:
				if !strings.Contains(got, record.Command) || !strings.Contains(got, test.recordPath) {
					t.Fatalf("dedicated remediation = %q, want command %q and record %q", got, record.Command, test.recordPath)
				}
				if strings.Contains(got, baselineDigestRegenerationHint) {
					t.Fatalf("dedicated remediation = %q, must not suggest sanctioned command", got)
				}
			case derivedOwnerFrozen:
				if !strings.Contains(got, "nothing regenerates this artifact") ||
					!strings.Contains(got, record.Reason) ||
					!strings.Contains(got, test.recordPath) {
					t.Fatalf("frozen remediation = %q, want no regenerator, reason %q, and record %q", got, record.Reason, test.recordPath)
				}
				if strings.Contains(got, baselineDigestRegenerationHint) {
					t.Fatalf("frozen remediation = %q, must not suggest sanctioned command", got)
				}
			}
		})
	}
}

func TestDerivedOwnershipRemediationRejectsUnownedArtifact(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/artifact.txt": &fstest.MapFile{Data: []byte("artifact\n")},
	}
	remediation, err := derivedArtifactRemediation(fixture, "derived", "derived/artifact.txt")
	if err == nil || !strings.Contains(err.Error(), "zero ownership records") {
		t.Fatalf("unowned remediation error = %v, want zero ownership records", err)
	}
	if remediation != "" {
		t.Fatalf("unowned remediation = %q, want no guessed action", remediation)
	}
}

func requireDerivedArtifactRemediation(t *testing.T, artifactPath string) string {
	t.Helper()

	remediation, err := derivedArtifactRemediation(os.DirFS("."), "testdata", artifactPath)
	if err != nil {
		t.Fatalf("read remediation for derived artifact %q: %v", artifactPath, err)
	}
	return remediation
}

func TestDerivedOwnershipDeclaresKnownBoundaries(t *testing.T) {
	t.Parallel()

	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}

	parity := resolved["testdata/parity-corpus"]
	if parity.Owner != derivedOwnerFrozen ||
		!strings.Contains(parity.Reason, "2026-07-30") ||
		!strings.Contains(parity.Reason, "tried") ||
		!strings.Contains(parity.Reason, "reverted") {
		t.Fatalf("parity corpus ownership = %+v, want frozen with the 2026-07-30 tried-and-reverted reason", parity)
	}

	const planCommand = "go test ./internal/baseline -count=1 -run TestBaselinePlanCharacterization -update-baseline-plan-characterization"
	plan := resolved["testdata/plan-characterization"]
	if plan.Owner != derivedOwnerDedicated || plan.Command != planCommand {
		t.Fatalf("plan characterization ownership = %+v, want dedicated command %q", plan, planCommand)
	}

	const diagnosticsCommand = "go test ./internal/baseline -run '^TestCatalogDiagnosticCharacterization$' -update-catalog-diagnostics -count=1"
	diagnostics := resolved["testdata/catalog.diagnostics.golden.json"]
	if diagnostics.Owner != derivedOwnerDedicated || diagnostics.Command != diagnosticsCommand {
		t.Fatalf("catalog diagnostic ownership = %+v, want dedicated command %q", diagnostics, diagnosticsCommand)
	}
}

func TestDerivedOwnershipValidationPreservesWholeTree(t *testing.T) {
	t.Parallel()

	roots := derivedDigestScanRoots(t)
	before := snapshotDerivedTree(t, roots)
	if _, err := validateDerivedOwnership(os.DirFS("."), roots); err != nil {
		t.Fatal(err)
	}
	after := snapshotDerivedTree(t, roots)
	if !reflect.DeepEqual(after, before) {
		t.Fatal("ownership validation changed the derived tree")
	}
}

func TestDeclaredStepRegenerationAndFrozenBoundaries(t *testing.T) {
	// Sequential: child commands deliberately rewrite one shared fixture.
	repository := newDerivedRegenerationFixture(t)
	baselineRoot := filepath.Join(repository, "internal", "baseline")
	fileSystem := os.DirFS(baselineRoot)
	roots := derivedDigestScanRoots(t)
	records, err := readDerivedOwnershipRecords(fileSystem, roots)
	if err != nil {
		t.Fatal(err)
	}
	resolved, err := validateDerivedOwnership(fileSystem, roots)
	if err != nil {
		t.Fatal(err)
	}
	artifactsByRecord := derivedArtifactsByRecord(t, fileSystem, roots, resolved)
	clean := snapshotDerivedTreeAt(t, baselineRoot, roots)
	cacheRoot := filepath.Join(repository, ".gocache")

	sanctioned := declaredSanctionedProbes(t, records)
	frozen := declaredFrozenProbes(t, records)

	recordPaths := make([]string, 0, len(records))
	for recordPath := range records {
		recordPaths = append(recordPaths, recordPath)
	}
	sort.Strings(recordPaths)
	var dedicatedRecordPath string
	for _, recordPath := range recordPaths {
		record := records[recordPath]
		if record.Owner != derivedOwnerDedicated {
			continue
		}
		if dedicatedRecordPath == "" {
			dedicatedRecordPath = recordPath
		}
		artifacts := artifactsByRecord[recordPath]
		if len(artifacts) == 0 {
			t.Fatalf("dedicated ownership record %q governs no artifacts", recordPath)
		}
		t.Run("dedicated/"+strings.ReplaceAll(recordPath, "/", "_"), func(t *testing.T) {
			rewrite := probesForPaths(artifacts, "dedicated")
			err := exerciseDeclaredRegenerationStep(
				t.Context(), repository, baselineRoot, cacheRoot, roots, clean,
				record.Command, rewrite, frozen,
			)
			if err != nil {
				t.Fatal(err)
			}
			assertDerivedFixtureRestored(t, baselineRoot, roots, clean)
		})
	}
	if dedicatedRecordPath == "" {
		t.Fatal("ownership manifest declares no dedicated regeneration step")
	}

	validDedicated := records[dedicatedRecordPath]
	negativeCases := []struct {
		name      string
		command   string
		wantError string
	}{
		{
			name:      "command does not exist",
			command:   "roundfix-declared-step-command-does-not-exist",
			wantError: "run declared command",
		},
		{
			name:      "declared flag is wrong",
			command:   validDedicated.Command + " -roundfix-deliberately-wrong-flag",
			wantError: "run declared command",
		},
		{
			name:      "command leaves artifacts unchanged",
			command:   "go version",
			wantError: "unchanged after deliberate perturbation",
		},
	}
	for _, test := range negativeCases {
		t.Run("failure/"+test.name, func(t *testing.T) {
			writeDedicatedCommandFixture(t, baselineRoot, dedicatedRecordPath, test.command)
			record, err := readDerivedOwnershipRecord(fileSystem, dedicatedRecordPath)
			if err != nil {
				t.Fatal(err)
			}
			err = exerciseDeclaredRegenerationStep(
				t.Context(), repository, baselineRoot, cacheRoot, roots, clean,
				record.Command,
				probesForPaths(artifactsByRecord[dedicatedRecordPath], "dedicated"),
				nil,
			)
			if err == nil || !strings.Contains(err.Error(), test.wantError) {
				t.Fatalf("declared-step error = %v, want %q", err, test.wantError)
			}
			assertDerivedFixtureRestored(t, baselineRoot, roots, clean)
		})
	}

	t.Run("sanctioned command rewrites sanctioned and preserves frozen", func(t *testing.T) {
		err := exerciseDeclaredRegenerationStep(
			t.Context(), repository, baselineRoot, cacheRoot, roots, clean,
			"make baseline-digests", sanctioned, frozen,
		)
		if err != nil {
			t.Fatal(err)
		}
		assertDerivedFixtureRestored(t, baselineRoot, roots, clean)
	})
}

func derivedDigestScanRoots(t *testing.T) []string {
	t.Helper()

	content, err := os.ReadFile("../../Makefile")
	if err != nil {
		t.Fatalf("read Makefile DERIVED_DIGEST_PATHS: %v", err)
	}
	const assignment = "DERIVED_DIGEST_PATHS :="
	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, assignment) {
			continue
		}
		fields := strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, assignment)))
		if len(fields) == 0 {
			t.Fatal("Makefile DERIVED_DIGEST_PATHS is empty")
		}
		roots := make([]string, 0, len(fields))
		for _, field := range fields {
			const packagePrefix = "internal/baseline/"
			if !strings.HasPrefix(field, packagePrefix) {
				t.Fatalf("derived scan path %q is outside internal/baseline", field)
			}
			roots = append(roots, strings.TrimPrefix(field, packagePrefix))
		}
		return roots
	}
	t.Fatal("Makefile has no DERIVED_DIGEST_PATHS assignment")
	return nil
}

type derivedArtifactSnapshot struct {
	content []byte
	mode    fs.FileMode
}

type derivedArtifactProbe struct {
	path    string
	owner   string
	perturb func([]byte) ([]byte, error)
}

func snapshotDerivedTree(t *testing.T, roots []string) map[string]derivedArtifactSnapshot {
	t.Helper()
	return snapshotDerivedTreeAt(t, ".", roots)
}

func snapshotDerivedTreeAt(
	t *testing.T,
	baselineRoot string,
	roots []string,
) map[string]derivedArtifactSnapshot {
	t.Helper()

	snapshot, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		t.Fatal(err)
	}
	return snapshot
}

func readDerivedTreeSnapshot(
	baselineRoot string,
	roots []string,
) (map[string]derivedArtifactSnapshot, error) {
	snapshot := make(map[string]derivedArtifactSnapshot)
	fileSystem := os.DirFS(baselineRoot)
	for _, root := range roots {
		if err := fs.WalkDir(fileSystem, root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return fmt.Errorf("walk derived tree %q: %w", filePath, walkErr)
			}
			if entry.IsDir() {
				return nil
			}
			content, err := fs.ReadFile(fileSystem, filePath)
			if err != nil {
				return fmt.Errorf("read derived artifact %q: %w", filePath, err)
			}
			info, err := entry.Info()
			if err != nil {
				return fmt.Errorf("stat derived artifact %q: %w", filePath, err)
			}
			snapshot[path.Clean(filePath)] = derivedArtifactSnapshot{
				content: append([]byte(nil), content...),
				mode:    info.Mode().Perm(),
			}
			return nil
		}); err != nil {
			return nil, fmt.Errorf("snapshot derived tree %q: %w", root, err)
		}
	}
	return snapshot, nil
}

func newDerivedRegenerationFixture(t *testing.T) string {
	t.Helper()

	sourceRoot := filepath.Clean(filepath.Join("..", ".."))
	fixtureRoot := t.TempDir()
	for _, directory := range []string{".agents", "internal", "skills"} {
		if err := os.CopyFS(
			filepath.Join(fixtureRoot, directory),
			os.DirFS(filepath.Join(sourceRoot, directory)),
		); err != nil {
			t.Fatalf("copy regeneration fixture directory %s: %v", directory, err)
		}
	}
	for _, fileName := range []string{"Makefile", "go.mod", "go.sum", "skills-lock.json"} {
		sourcePath := filepath.Join(sourceRoot, fileName)
		content, err := os.ReadFile(sourcePath)
		if err != nil {
			t.Fatalf("read regeneration fixture file %s: %v", fileName, err)
		}
		info, err := os.Stat(sourcePath)
		if err != nil {
			t.Fatalf("stat regeneration fixture file %s: %v", fileName, err)
		}
		if err := os.WriteFile(filepath.Join(fixtureRoot, fileName), content, info.Mode().Perm()); err != nil {
			t.Fatalf("copy regeneration fixture file %s: %v", fileName, err)
		}
	}
	return fixtureRoot
}

func derivedArtifactsByRecord(
	t *testing.T,
	fileSystem fs.FS,
	roots []string,
	resolved map[string]derivedOwnershipRecord,
) map[string][]string {
	t.Helper()

	artifacts := make(map[string][]string)
	for artifactPath := range resolved {
		info, err := fs.Stat(fileSystem, artifactPath)
		if err != nil {
			t.Fatalf("stat resolved derived path %q: %v", artifactPath, err)
		}
		if !info.Mode().IsRegular() {
			continue
		}
		var recordPaths []string
		for _, root := range roots {
			if !pathWithinDerivedScanRoot(artifactPath, root) {
				continue
			}
			recordPaths, err = resolveDerivedOwnershipRecordPaths(
				fileSystem, root, artifactPath, false,
			)
			if err != nil {
				t.Fatalf("resolve ownership for %q: %v", artifactPath, err)
			}
			break
		}
		if len(recordPaths) != 1 {
			t.Fatalf("resolved artifact %q has ownership records %v", artifactPath, recordPaths)
		}
		artifacts[recordPaths[0]] = append(artifacts[recordPaths[0]], artifactPath)
	}
	for recordPath := range artifacts {
		sort.Strings(artifacts[recordPath])
	}
	return artifacts
}

func declaredSanctionedProbes(
	t *testing.T,
	records map[string]derivedOwnershipRecord,
) []derivedArtifactProbe {
	t.Helper()

	probes := map[string]derivedArtifactProbe{
		"assets/setups/_ownership.yml": {
			path: "assets/setups/go-cli.json", owner: "sanctioned",
		},
		"assets/source-baselines/_ownership.yml": {
			path:  "assets/source-baselines/baseline.standard-typescript-monorepo-0.0.1/manifest.json",
			owner: "sanctioned",
		},
		"assets/formatter-fixtures/_ownership.yml": {
			path:  "assets/formatter-fixtures/standard-typescript-monorepo/golden/AGENTS.md",
			owner: "sanctioned",
		},
		"assets/profiles/_ownership.yml": {
			path:  "assets/profiles/standard-typescript-monorepo.json",
			owner: "sanctioned", perturb: perturbFormatterGoldenDigest,
		},
		"testdata/_ownership.yml": {
			path: "testdata/catalog.digest", owner: "sanctioned",
		},
	}
	return probesForDeclaredOwner(t, records, derivedOwnerSanctioned, probes)
}

func declaredFrozenProbes(
	t *testing.T,
	records map[string]derivedOwnershipRecord,
) []derivedArtifactProbe {
	t.Helper()

	probes := map[string]derivedArtifactProbe{
		"testdata/parity-corpus/_ownership.yml": {
			path: "testdata/parity-corpus/v1/matrix.json", owner: "frozen",
		},
		"testdata/legacy-v2/_ownership.yml": {
			path: "testdata/legacy-v2/assets/coverage.json", owner: "frozen",
		},
		"testdata/adr-lifecycle/_ownership.yml": {
			path: "testdata/adr-lifecycle/accepted.md", owner: "frozen",
		},
	}
	return probesForDeclaredOwner(t, records, derivedOwnerFrozen, probes)
}

func probesForDeclaredOwner(
	t *testing.T,
	records map[string]derivedOwnershipRecord,
	owner derivedOwnershipOwner,
	probes map[string]derivedArtifactProbe,
) []derivedArtifactProbe {
	t.Helper()

	paths := make([]string, 0, len(probes))
	for recordPath, record := range records {
		if record.Owner != owner {
			continue
		}
		if _, ok := probes[recordPath]; !ok {
			t.Fatalf("%s ownership record %q has no regeneration probe", owner, recordPath)
		}
		paths = append(paths, recordPath)
	}
	if len(paths) != len(probes) {
		t.Fatalf("%s regeneration probes = %d, ownership records = %d", owner, len(probes), len(paths))
	}
	sort.Strings(paths)
	result := make([]derivedArtifactProbe, 0, len(paths))
	for _, recordPath := range paths {
		result = append(result, probes[recordPath])
	}
	return result
}

func probesForPaths(paths []string, owner string) []derivedArtifactProbe {
	probes := make([]derivedArtifactProbe, 0, len(paths))
	for _, artifactPath := range paths {
		probes = append(probes, derivedArtifactProbe{path: artifactPath, owner: owner})
	}
	return probes
}

func cloneDerivedProbes(probes []derivedArtifactProbe) []derivedArtifactProbe {
	return append([]derivedArtifactProbe(nil), probes...)
}

func exerciseDeclaredRegenerationStep(
	ctx context.Context,
	repository string,
	baselineRoot string,
	cacheRoot string,
	roots []string,
	restoreTo map[string]derivedArtifactSnapshot,
	command string,
	rewrite []derivedArtifactProbe,
	untouched []derivedArtifactProbe,
) (resultErr error) {
	before, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	defer func() {
		if err := restoreDerivedTree(baselineRoot, roots, restoreTo); resultErr == nil && err != nil {
			resultErr = err
		}
	}()

	allProbes := append(cloneDerivedProbes(rewrite), untouched...)
	if err := perturbDerivedArtifacts(baselineRoot, before, allProbes); err != nil {
		return err
	}
	perturbed, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	if err := runDeclaredRegenerationStep(ctx, repository, cacheRoot, command); err != nil {
		return err
	}
	after, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	for _, probe := range rewrite {
		got, ok := after[probe.path]
		if !ok {
			return fmt.Errorf("declared command %q removed claimed artifact %q", command, probe.path)
		}
		if bytes.Equal(got.content, perturbed[probe.path].content) {
			return fmt.Errorf(
				"declared command %q left artifact %q unchanged after deliberate perturbation",
				command, probe.path,
			)
		}
		if !reflect.DeepEqual(got, before[probe.path]) {
			return fmt.Errorf(
				"declared command %q did not restore claimed artifact %q: %s",
				command,
				probe.path,
				firstDerivedContentDifference(before[probe.path].content, got.content),
			)
		}
	}
	for _, probe := range untouched {
		if !reflect.DeepEqual(after[probe.path], perturbed[probe.path]) {
			return fmt.Errorf(
				"declared command %q rewrote %s artifact %q outside its ownership",
				command, probe.owner, probe.path,
			)
		}
	}
	expected := cloneDerivedSnapshot(before)
	for _, probe := range untouched {
		expected[probe.path] = perturbed[probe.path]
	}
	if !reflect.DeepEqual(after, expected) {
		return fmt.Errorf("declared command %q changed artifacts outside its declared ownership", command)
	}
	return nil
}

func runDeclaredRegenerationStep(
	ctx context.Context,
	repository string,
	cacheRoot string,
	command string,
) error {
	cmd := exec.CommandContext(ctx, "sh", "-c", command)
	cmd.Dir = repository
	cmd.Env = append(os.Environ(), "GOCACHE="+cacheRoot, "GOFLAGS=-buildvcs=false")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("run declared command %q: %w\n%s", command, err, output)
	}
	return nil
}

func perturbDerivedArtifacts(
	baselineRoot string,
	before map[string]derivedArtifactSnapshot,
	probes []derivedArtifactProbe,
) error {
	seen := make(map[string]struct{}, len(probes))
	for _, probe := range probes {
		if _, duplicate := seen[probe.path]; duplicate {
			return fmt.Errorf("artifact %q has more than one regeneration probe", probe.path)
		}
		seen[probe.path] = struct{}{}
		snapshot, ok := before[probe.path]
		if !ok {
			return fmt.Errorf("regeneration probe artifact %q is absent", probe.path)
		}
		perturb := probe.perturb
		if perturb == nil {
			perturb = appendHarmlessWhitespace
		}
		content, err := perturb(snapshot.content)
		if err != nil {
			return fmt.Errorf("perturb artifact %q: %w", probe.path, err)
		}
		if bytes.Equal(content, snapshot.content) {
			return fmt.Errorf("perturbation left artifact %q unchanged", probe.path)
		}
		if err := os.WriteFile(
			filepath.Join(baselineRoot, filepath.FromSlash(probe.path)),
			content,
			snapshot.mode,
		); err != nil {
			return fmt.Errorf("write perturbed artifact %q: %w", probe.path, err)
		}
	}
	return nil
}

func appendHarmlessWhitespace(content []byte) ([]byte, error) {
	return append(append([]byte(nil), content...), ' ', '\n'), nil
}

func firstDerivedContentDifference(want []byte, got []byte) string {
	limit := min(len(want), len(got))
	index := 0
	for index < limit && want[index] == got[index] {
		index++
	}
	contextEnd := min(index+80, limit)
	return fmt.Sprintf(
		"first byte %d, want length %d and %q, got length %d and %q",
		index,
		len(want),
		want[index:contextEnd],
		len(got),
		got[index:contextEnd],
	)
}

func perturbFormatterGoldenDigest(content []byte) ([]byte, error) {
	const prefix = `"goldenDigest": "`
	start := bytes.Index(content, []byte(prefix))
	if start == -1 {
		return nil, fmt.Errorf("goldenDigest field is absent")
	}
	start += len(prefix)
	endOffset := bytes.IndexByte(content[start:], '"')
	if endOffset <= 0 {
		return nil, fmt.Errorf("goldenDigest value is malformed")
	}
	result := append([]byte(nil), content...)
	replacement := byte('0')
	if bytes.Count(result[start:start+endOffset], []byte{'0'}) == endOffset {
		replacement = '1'
	}
	for index := start; index < start+endOffset; index++ {
		result[index] = replacement
	}
	return result, nil
}

func writeDedicatedCommandFixture(
	t *testing.T,
	baselineRoot string,
	recordPath string,
	command string,
) {
	t.Helper()

	content := "owner: dedicated\ncommand: >-\n  " +
		strings.ReplaceAll(command, "\n", "\n  ") +
		"\nreason: deliberately invalid declared-step fixture\n"
	if err := os.WriteFile(
		filepath.Join(baselineRoot, filepath.FromSlash(recordPath)),
		[]byte(content),
		0o644,
	); err != nil {
		t.Fatalf("write declared-step fixture %q: %v", recordPath, err)
	}
}

func restoreDerivedTree(
	baselineRoot string,
	roots []string,
	snapshot map[string]derivedArtifactSnapshot,
) error {
	current, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	for artifactPath := range current {
		if _, existed := snapshot[artifactPath]; existed {
			continue
		}
		if err := os.Remove(filepath.Join(baselineRoot, filepath.FromSlash(artifactPath))); err != nil {
			return fmt.Errorf("remove generated fixture artifact %q: %w", artifactPath, err)
		}
	}
	paths := make([]string, 0, len(snapshot))
	for artifactPath := range snapshot {
		paths = append(paths, artifactPath)
	}
	sort.Strings(paths)
	for _, artifactPath := range paths {
		artifact := snapshot[artifactPath]
		fullPath := filepath.Join(baselineRoot, filepath.FromSlash(artifactPath))
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("restore fixture directory for %q: %w", artifactPath, err)
		}
		if err := os.WriteFile(fullPath, artifact.content, artifact.mode); err != nil {
			return fmt.Errorf("restore fixture artifact %q: %w", artifactPath, err)
		}
	}
	return nil
}

func cloneDerivedSnapshot(
	snapshot map[string]derivedArtifactSnapshot,
) map[string]derivedArtifactSnapshot {
	clone := make(map[string]derivedArtifactSnapshot, len(snapshot))
	for artifactPath, artifact := range snapshot {
		clone[artifactPath] = artifact
	}
	return clone
}

func assertDerivedFixtureRestored(
	t *testing.T,
	baselineRoot string,
	roots []string,
	want map[string]derivedArtifactSnapshot,
) {
	t.Helper()

	got := snapshotDerivedTreeAt(t, baselineRoot, roots)
	if !reflect.DeepEqual(got, want) {
		t.Fatal("declared-step test did not restore the derived fixture")
	}
}
