// Suite: derived artifact ownership
// Invariant: every path in the Makefile's derived scan resolves to exactly one validated ownership record.
// Boundary IN: DERIVED_DIGEST_PATHS, ownership YAML, and read-only path resolution.
// Boundary OUT: executing dedicated commands, widening BASELINE_DIGEST_STEPS, and remediation diagnostics.

package baseline

import (
	"io/fs"
	"os"
	"path"
	"reflect"
	"strings"
	"testing"
	"testing/fstest"
)

func TestDerivedOwnershipIsExhaustive(t *testing.T) {
	t.Parallel()

	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}
	if len(resolved) == 0 {
		t.Fatal("derived scan resolved no paths")
	}
}

func TestDerivedOwnershipRejectsUnclassifiedArtifact(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/unclassified.txt": &fstest.MapFile{Data: []byte("unclassified\n")},
	}
	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "zero ownership records") {
		t.Fatalf("unclassified artifact error = %v, want zero ownership records", err)
	}
}

func TestDerivedOwnershipRejectsMultipleRecords(t *testing.T) {
	t.Parallel()

	record := []byte("owner: sanctioned\nreason: fixture\n")
	fixture := fstest.MapFS{
		"derived/_ownership.yml":  &fstest.MapFile{Data: record},
		"derived/_ownership.yaml": &fstest.MapFile{Data: record},
		"derived/artifact.txt":    &fstest.MapFile{Data: []byte("artifact\n")},
	}
	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "more than one ownership record") {
		t.Fatalf("ambiguous ownership error = %v, want more than one ownership record", err)
	}
}

func TestDerivedOwnershipValidatesRecords(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		record    string
		wantError string
	}{
		{
			name:   "sanctioned with reason",
			record: "owner: sanctioned\nreason: regenerated by the sanctioned command\n",
		},
		{
			name:   "frozen with reason",
			record: "owner: frozen\nreason: intentionally regenerated by nothing\n",
		},
		{
			name: "dedicated with command",
			record: "owner: dedicated\n" +
				"command: go test ./internal/baseline -run TestFixture\n" +
				"reason: uses a dedicated regeneration step\n",
		},
		{
			name:      "unknown owner",
			record:    "owner: inferred\nreason: invalid owner\n",
			wantError: "is not sanctioned, dedicated, or frozen",
		},
		{
			name:      "missing reason",
			record:    "owner: sanctioned\n",
			wantError: "reason is required",
		},
		{
			name:      "dedicated missing command",
			record:    "owner: dedicated\nreason: missing exact invocation\n",
			wantError: "command is required for dedicated ownership",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			fixture := fstest.MapFS{
				"derived/_ownership.yml": &fstest.MapFile{Data: []byte(test.record)},
				"derived/artifact.txt":   &fstest.MapFile{Data: []byte("artifact\n")},
			}
			_, err := validateDerivedOwnership(fixture, []string{"derived"})
			if test.wantError == "" {
				if err != nil {
					t.Fatal(err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), test.wantError) {
				t.Fatalf("validation error = %v, want %q", err, test.wantError)
			}
		})
	}
}

func TestDerivedOwnershipDeclaresKnownBoundaries(t *testing.T) {
	t.Parallel()

	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}

	parity := resolved["testdata/parity-corpus"]
	if parity.Owner != derivedOwnerFrozen ||
		!strings.Contains(parity.Reason, "2026-07-30") ||
		!strings.Contains(parity.Reason, "tried") ||
		!strings.Contains(parity.Reason, "reverted") {
		t.Fatalf("parity corpus ownership = %+v, want frozen with the 2026-07-30 tried-and-reverted reason", parity)
	}

	const planCommand = "go test ./internal/baseline -count=1 -run TestBaselinePlanCharacterization -update-baseline-plan-characterization"
	plan := resolved["testdata/plan-characterization"]
	if plan.Owner != derivedOwnerDedicated || plan.Command != planCommand {
		t.Fatalf("plan characterization ownership = %+v, want dedicated command %q", plan, planCommand)
	}

	const diagnosticsCommand = "go test ./internal/baseline -run '^TestCatalogDiagnosticCharacterization$' -update-catalog-diagnostics -count=1"
	diagnostics := resolved["testdata/catalog.diagnostics.golden.json"]
	if diagnostics.Owner != derivedOwnerDedicated || diagnostics.Command != diagnosticsCommand {
		t.Fatalf("catalog diagnostic ownership = %+v, want dedicated command %q", diagnostics, diagnosticsCommand)
	}
}

func TestDerivedOwnershipValidationPreservesWholeTree(t *testing.T) {
	t.Parallel()

	roots := derivedDigestScanRoots(t)
	before := snapshotDerivedTree(t, roots)
	if _, err := validateDerivedOwnership(os.DirFS("."), roots); err != nil {
		t.Fatal(err)
	}
	after := snapshotDerivedTree(t, roots)
	if !reflect.DeepEqual(after, before) {
		t.Fatal("ownership validation changed the derived tree")
	}
}

func derivedDigestScanRoots(t *testing.T) []string {
	t.Helper()

	content, err := os.ReadFile("../../Makefile")
	if err != nil {
		t.Fatalf("read Makefile DERIVED_DIGEST_PATHS: %v", err)
	}
	const assignment = "DERIVED_DIGEST_PATHS :="
	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, assignment) {
			continue
		}
		fields := strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, assignment)))
		if len(fields) == 0 {
			t.Fatal("Makefile DERIVED_DIGEST_PATHS is empty")
		}
		roots := make([]string, 0, len(fields))
		for _, field := range fields {
			const packagePrefix = "internal/baseline/"
			if !strings.HasPrefix(field, packagePrefix) {
				t.Fatalf("derived scan path %q is outside internal/baseline", field)
			}
			roots = append(roots, strings.TrimPrefix(field, packagePrefix))
		}
		return roots
	}
	t.Fatal("Makefile has no DERIVED_DIGEST_PATHS assignment")
	return nil
}

func snapshotDerivedTree(t *testing.T, roots []string) map[string]string {
	t.Helper()

	snapshot := make(map[string]string)
	fileSystem := os.DirFS(".")
	for _, root := range roots {
		if err := fs.WalkDir(fileSystem, root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			content, err := fs.ReadFile(fileSystem, filePath)
			if err != nil {
				return err
			}
			snapshot[path.Clean(filePath)] = string(content)
			return nil
		}); err != nil {
			t.Fatalf("snapshot derived tree %q: %v", root, err)
		}
	}
	return snapshot
}
