// Suite: derived artifact ownership
// Invariant: every path in the Makefile's derived scan resolves to exactly one ownership record that matches measured regeneration behavior.
// Boundary IN: DERIVED_DIGEST_PATHS, ownership YAML, regeneration commands, path resolution, and remediation diagnostics.
// Boundary OUT: product decisions about which artifacts should be regenerated.

package baseline

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"
	"testing"
	"testing/fstest"
)

func TestDerivedOwnershipIsExhaustive(t *testing.T) {
	t.Parallel()

	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}
	if len(resolved) == 0 {
		t.Fatal("derived scan resolved no paths")
	}
}

func TestDerivedOwnershipRejectsUnclassifiedArtifact(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/unclassified.txt": &fstest.MapFile{Data: []byte("unclassified\n")},
	}
	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "zero ownership records") {
		t.Fatalf("unclassified artifact error = %v, want zero ownership records", err)
	}
}

func TestDerivedOwnershipRejectsMultipleRecords(t *testing.T) {
	t.Parallel()

	record := []byte("owner: sanctioned\nreason: fixture\n")
	fixture := fstest.MapFS{
		"derived/_ownership.yml":  &fstest.MapFile{Data: record},
		"derived/_ownership.yaml": &fstest.MapFile{Data: record},
		"derived/artifact.txt":    &fstest.MapFile{Data: []byte("artifact\n")},
	}
	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "more than one ownership record") {
		t.Fatalf("ambiguous ownership error = %v, want more than one ownership record", err)
	}
}

func TestDerivedOwnershipExceptionOverridesDirectory(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/_ownership.yml": &fstest.MapFile{Data: []byte(
			"owner: frozen\n" +
				"reason: frozen fixture\n" +
				"exceptions:\n" +
				"  - path: nested/generated.json\n" +
				"    owner: sanctioned\n",
		)},
		"derived/nested/_ownership.yml": &fstest.MapFile{Data: []byte(
			"owner: frozen\nreason: nested frozen fixture\n",
		)},
		"derived/nested/generated.json": &fstest.MapFile{Data: []byte("generated\n")},
		"derived/nested/frozen.json":    &fstest.MapFile{Data: []byte("frozen\n")},
	}

	resolved, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err != nil {
		t.Fatal(err)
	}
	if got := resolved["derived/nested/generated.json"].Owner; got != derivedOwnerSanctioned {
		t.Fatalf("exception owner = %q, want %q", got, derivedOwnerSanctioned)
	}
	if got := resolved["derived/nested/frozen.json"].Owner; got != derivedOwnerFrozen {
		t.Fatalf("directory owner = %q, want %q", got, derivedOwnerFrozen)
	}
}

func TestDerivedOwnershipRejectsDuplicateExceptions(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/_ownership.yml": &fstest.MapFile{Data: []byte(
			"owner: frozen\n" +
				"reason: frozen fixture\n" +
				"exceptions:\n" +
				"  - path: nested/artifact.json\n" +
				"    owner: sanctioned\n",
		)},
		"derived/nested/_ownership.yml": &fstest.MapFile{Data: []byte(
			"owner: frozen\n" +
				"reason: nested frozen fixture\n" +
				"exceptions:\n" +
				"  - path: artifact.json\n" +
				"    owner: sanctioned\n",
		)},
		"derived/nested/artifact.json": &fstest.MapFile{Data: []byte("artifact\n")},
	}

	_, err := validateDerivedOwnership(fixture, []string{"derived"})
	if err == nil || !strings.Contains(err.Error(), "more than one ownership exception") {
		t.Fatalf("duplicate exception error = %v, want more than one ownership exception", err)
	}
}

func TestDerivedOwnershipRejectsExceptionOutsideRecordDirectory(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/owned/_ownership.yml": &fstest.MapFile{Data: []byte(
			"owner: frozen\n" +
				"reason: frozen fixture\n" +
				"exceptions:\n" +
				"  - path: ../outside.json\n" +
				"    owner: sanctioned\n",
		)},
		"derived/owned/artifact.json": &fstest.MapFile{Data: []byte("artifact\n")},
		"derived/outside.json":        &fstest.MapFile{Data: []byte("outside\n")},
	}

	_, err := validateDerivedOwnership(fixture, []string{"derived/owned"})
	if err == nil || !strings.Contains(err.Error(), "outside record directory") {
		t.Fatalf("escaping exception error = %v, want outside record directory", err)
	}
}

func TestDerivedOwnershipValidatesRecords(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		record    string
		wantError string
	}{
		{
			name:   "sanctioned with reason",
			record: "owner: sanctioned\nreason: regenerated by the sanctioned command\n",
		},
		{
			name:   "frozen with reason",
			record: "owner: frozen\nreason: intentionally regenerated by nothing\n",
		},
		{
			name: "dedicated with command",
			record: "owner: dedicated\n" +
				"command: go test ./internal/baseline -run TestFixture\n" +
				"reason: uses a dedicated regeneration step\n",
		},
		{
			name:      "unknown owner",
			record:    "owner: inferred\nreason: invalid owner\n",
			wantError: "is not sanctioned, dedicated, or frozen",
		},
		{
			name:      "missing reason",
			record:    "owner: sanctioned\n",
			wantError: "reason is required",
		},
		{
			name:      "dedicated missing command",
			record:    "owner: dedicated\nreason: missing exact invocation\n",
			wantError: "command is required for dedicated ownership",
		},
		{
			name: "frozen exception missing reason",
			record: "owner: sanctioned\n" +
				"reason: parent sanctioned reason\n" +
				"exceptions:\n" +
				"  - path: artifact.txt\n" +
				"    owner: frozen\n",
			wantError: "reason is required for frozen ownership exception",
		},
		{
			name: "dedicated exception missing command",
			record: "owner: sanctioned\n" +
				"command: go test ./internal/baseline -run TestParent\n" +
				"reason: parent sanctioned reason\n" +
				"exceptions:\n" +
				"  - path: artifact.txt\n" +
				"    owner: dedicated\n",
			wantError: "command is required for dedicated ownership exception",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			fixture := fstest.MapFS{
				"derived/_ownership.yml": &fstest.MapFile{Data: []byte(test.record)},
				"derived/artifact.txt":   &fstest.MapFile{Data: []byte("artifact\n")},
			}
			_, err := validateDerivedOwnership(fixture, []string{"derived"})
			if test.wantError == "" {
				if err != nil {
					t.Fatal(err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), test.wantError) {
				t.Fatalf("validation error = %v, want %q", err, test.wantError)
			}
		})
	}
}

func TestDerivedOwnershipRemediationDiagnostics(t *testing.T) {
	t.Parallel()
	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name       string
		scanRoot   string
		artifact   string
		recordPath string
		owner      derivedOwnershipOwner
	}{
		{
			name:       "sanctioned setup",
			scanRoot:   "assets/setups",
			artifact:   "assets/setups/go-cli.json",
			recordPath: "assets/setups/_ownership.yml",
			owner:      derivedOwnerSanctioned,
		},
		{
			name:       "sanctioned plan characterization",
			scanRoot:   "testdata",
			artifact:   "testdata/plan-characterization/clean-adoption.golden.json",
			recordPath: "testdata/plan-characterization/_ownership.yml",
			owner:      derivedOwnerSanctioned,
		},
		{
			name:       "sanctioned parity exception",
			scanRoot:   "testdata",
			artifact:   "testdata/parity-corpus/v1/fixtures/asset-sync.json",
			recordPath: "testdata/parity-corpus/_ownership.yml",
			owner:      derivedOwnerSanctioned,
		},
		{
			name:       "frozen parity path",
			scanRoot:   "testdata",
			artifact:   "testdata/parity-corpus/v1/matrix.json",
			recordPath: "testdata/parity-corpus/_ownership.yml",
			owner:      derivedOwnerFrozen,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			declaredRecord, err := readDerivedOwnershipRecord(os.DirFS("."), test.recordPath)
			if err != nil {
				t.Fatal(err)
			}
			record, ok := resolved[test.artifact]
			if !ok {
				t.Fatalf("derived artifact %q has no resolved ownership", test.artifact)
			}
			if record.Owner != test.owner {
				t.Fatalf("derived artifact %q owner = %q, want %q", test.artifact, record.Owner, test.owner)
			}
			got, err := derivedArtifactRemediation(os.DirFS("."), test.scanRoot, test.artifact)
			if err != nil {
				t.Fatal(err)
			}

			switch test.owner {
			case derivedOwnerSanctioned:
				if got != baselineDigestRegenerationHint {
					t.Fatalf("sanctioned remediation = %q, want unchanged %q", got, baselineDigestRegenerationHint)
				}
			case derivedOwnerDedicated:
				if !strings.Contains(got, declaredRecord.Command) || !strings.Contains(got, test.recordPath) {
					t.Fatalf("dedicated remediation = %q, want command %q and record %q", got, declaredRecord.Command, test.recordPath)
				}
				if strings.Contains(got, baselineDigestRegenerationHint) {
					t.Fatalf("dedicated remediation = %q, must not suggest sanctioned command", got)
				}
			case derivedOwnerFrozen:
				if !strings.Contains(got, "nothing regenerates this artifact") ||
					!strings.Contains(got, declaredRecord.Reason) ||
					!strings.Contains(got, test.recordPath) {
					t.Fatalf("frozen remediation = %q, want no regenerator, reason %q, and record %q", got, declaredRecord.Reason, test.recordPath)
				}
				if strings.Contains(got, baselineDigestRegenerationHint) {
					t.Fatalf("frozen remediation = %q, must not suggest sanctioned command", got)
				}
			}
		})
	}

	t.Run("dedicated fixture", func(t *testing.T) {
		t.Parallel()

		const (
			recordPath = "derived/_ownership.yml"
			command    = "go test ./internal/baseline -run TestFixture -update-fixture"
		)
		fixture := fstest.MapFS{
			recordPath: &fstest.MapFile{Data: []byte(
				"owner: dedicated\ncommand: " + command + "\nreason: fixture\n",
			)},
			"derived/artifact.txt": &fstest.MapFile{Data: []byte("artifact\n")},
		}
		got, err := derivedArtifactRemediation(fixture, "derived", "derived/artifact.txt")
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(got, command) || !strings.Contains(got, recordPath) {
			t.Fatalf("dedicated remediation = %q, want command %q and record %q", got, command, recordPath)
		}
		if strings.Contains(got, baselineDigestRegenerationHint) {
			t.Fatalf("dedicated remediation = %q, must not suggest sanctioned command", got)
		}
	})
}

func TestDerivedOwnershipExceptionUsesOwnRemediationMetadata(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		exception   string
		want        string
		parentValue string
	}{
		{
			name: "frozen exception uses its reason",
			exception: "    owner: frozen\n" +
				"    reason: exception frozen reason\n",
			want:        "exception frozen reason",
			parentValue: "parent sanctioned reason",
		},
		{
			name: "dedicated exception uses its command",
			exception: "    owner: dedicated\n" +
				"    command: go test ./internal/baseline -run TestException -update-exception\n",
			want:        "go test ./internal/baseline -run TestException -update-exception",
			parentValue: "go test ./internal/baseline -run TestParent -update-parent",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			fixture := fstest.MapFS{
				"derived/_ownership.yml": &fstest.MapFile{Data: []byte(
					"owner: sanctioned\n" +
						"command: go test ./internal/baseline -run TestParent -update-parent\n" +
						"reason: parent sanctioned reason\n" +
						"exceptions:\n" +
						"  - path: artifact.txt\n" +
						test.exception,
				)},
				"derived/artifact.txt": &fstest.MapFile{Data: []byte("artifact\n")},
			}

			got, err := derivedArtifactRemediation(fixture, "derived", "derived/artifact.txt")
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(got, test.want) {
				t.Fatalf("exception remediation = %q, want exception metadata %q", got, test.want)
			}
			if strings.Contains(got, test.parentValue) {
				t.Fatalf("exception remediation = %q, must not inherit parent metadata %q", got, test.parentValue)
			}
		})
	}
}

func TestDerivedOwnershipRemediationRejectsUnownedArtifact(t *testing.T) {
	t.Parallel()

	fixture := fstest.MapFS{
		"derived/artifact.txt": &fstest.MapFile{Data: []byte("artifact\n")},
	}
	remediation, err := derivedArtifactRemediation(fixture, "derived", "derived/artifact.txt")
	if err == nil || !strings.Contains(err.Error(), "zero ownership records") {
		t.Fatalf("unowned remediation error = %v, want zero ownership records", err)
	}
	if remediation != "" {
		t.Fatalf("unowned remediation = %q, want no guessed action", remediation)
	}
}

func requireDerivedArtifactRemediation(t *testing.T, artifactPath string) string {
	t.Helper()

	remediation, err := derivedArtifactRemediation(os.DirFS("."), "testdata", artifactPath)
	if err != nil {
		t.Fatalf("read remediation for derived artifact %q: %v", artifactPath, err)
	}
	return remediation
}

func TestDerivedOwnershipDeclaresKnownBoundaries(t *testing.T) {
	t.Parallel()

	resolved, err := validateDerivedOwnership(os.DirFS("."), derivedDigestScanRoots(t))
	if err != nil {
		t.Fatal(err)
	}

	const parityRecordPath = "testdata/parity-corpus/_ownership.yml"
	parity, err := readDerivedOwnershipRecord(os.DirFS("."), parityRecordPath)
	if err != nil {
		t.Fatal(err)
	}
	if parity.Owner != derivedOwnerFrozen || !strings.Contains(parity.Reason, "2026-07-30") {
		t.Fatalf("parity corpus ownership = %+v, want frozen with the retained corpus decision", parity)
	}
	parityExceptions := map[string]derivedOwnershipOwner{
		"v1/manifest.json":            derivedOwnerSanctioned,
		"v1/fixtures/asset-sync.json": derivedOwnerSanctioned,
	}
	if len(parity.Exceptions) != len(parityExceptions) {
		t.Fatalf("parity corpus exceptions = %+v, want exactly %v", parity.Exceptions, parityExceptions)
	}
	for _, exception := range parity.Exceptions {
		if owner, ok := parityExceptions[exception.Path]; !ok || owner != exception.Owner {
			t.Fatalf("parity corpus exception = %+v, want exactly %v", exception, parityExceptions)
		}
	}

	for artifactPath, record := range resolved {
		if !strings.HasPrefix(artifactPath, "testdata/parity-corpus/") {
			continue
		}
		info, err := fs.Stat(os.DirFS("."), artifactPath)
		if err != nil {
			t.Fatalf("stat parity corpus path %q: %v", artifactPath, err)
		}
		if !info.Mode().IsRegular() {
			continue
		}
		relativePath := strings.TrimPrefix(artifactPath, "testdata/parity-corpus/")
		want := derivedOwnerFrozen
		if exceptionOwner, ok := parityExceptions[relativePath]; ok {
			want = exceptionOwner
		}
		if record.Owner != want {
			t.Errorf("parity corpus path %q owner = %q, want %q", relativePath, record.Owner, want)
		}
	}

	plan := resolved["testdata/plan-characterization"]
	if plan.Owner != derivedOwnerSanctioned || !strings.Contains(plan.Reason, "make baseline-digests") {
		t.Fatalf("plan characterization ownership = %+v, want sanctioned command coverage", plan)
	}

	diagnostics := resolved["testdata/catalog.diagnostics.golden.json"]
	if diagnostics.Owner != derivedOwnerSanctioned || !strings.Contains(diagnostics.Reason, "make baseline-digests") {
		t.Fatalf("catalog diagnostic ownership = %+v, want sanctioned command coverage", diagnostics)
	}
}

func TestDerivedOwnershipValidationPreservesWholeTree(t *testing.T) {
	t.Parallel()

	roots := derivedDigestScanRoots(t)
	before := snapshotDerivedTree(t, roots)
	if _, err := validateDerivedOwnership(os.DirFS("."), roots); err != nil {
		t.Fatal(err)
	}
	after := snapshotDerivedTree(t, roots)
	if !reflect.DeepEqual(after, before) {
		t.Fatal("ownership validation changed the derived tree")
	}
}

func derivedDigestScanRoots(t *testing.T) []string {
	t.Helper()

	content, err := os.ReadFile("../../Makefile")
	if err != nil {
		t.Fatalf("read Makefile DERIVED_DIGEST_PATHS: %v", err)
	}
	const assignment = "DERIVED_DIGEST_PATHS :="
	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, assignment) {
			continue
		}
		fields := strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, assignment)))
		if len(fields) == 0 {
			t.Fatal("Makefile DERIVED_DIGEST_PATHS is empty")
		}
		roots := make([]string, 0, len(fields))
		for _, field := range fields {
			const packagePrefix = "internal/baseline/"
			if !strings.HasPrefix(field, packagePrefix) {
				t.Fatalf("derived scan path %q is outside internal/baseline", field)
			}
			roots = append(roots, strings.TrimPrefix(field, packagePrefix))
		}
		return roots
	}
	t.Fatal("Makefile has no DERIVED_DIGEST_PATHS assignment")
	return nil
}

type derivedArtifactSnapshot struct {
	content []byte
	mode    fs.FileMode
}

type derivedArtifactProbe struct {
	path    string
	owner   string
	perturb func([]byte) ([]byte, error)
}

func snapshotDerivedTree(t *testing.T, roots []string) map[string]derivedArtifactSnapshot {
	t.Helper()
	return snapshotDerivedTreeAt(t, ".", roots)
}

func snapshotDerivedTreeAt(
	t *testing.T,
	baselineRoot string,
	roots []string,
) map[string]derivedArtifactSnapshot {
	t.Helper()

	snapshot, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		t.Fatal(err)
	}
	return snapshot
}

func readDerivedTreeSnapshot(
	baselineRoot string,
	roots []string,
) (map[string]derivedArtifactSnapshot, error) {
	snapshot := make(map[string]derivedArtifactSnapshot)
	fileSystem := os.DirFS(baselineRoot)
	for _, root := range roots {
		if err := fs.WalkDir(fileSystem, root, func(filePath string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return fmt.Errorf("walk derived tree %q: %w", filePath, walkErr)
			}
			if entry.IsDir() {
				return nil
			}
			content, err := fs.ReadFile(fileSystem, filePath)
			if err != nil {
				return fmt.Errorf("read derived artifact %q: %w", filePath, err)
			}
			info, err := entry.Info()
			if err != nil {
				return fmt.Errorf("stat derived artifact %q: %w", filePath, err)
			}
			snapshot[path.Clean(filePath)] = derivedArtifactSnapshot{
				content: append([]byte(nil), content...),
				mode:    info.Mode().Perm(),
			}
			return nil
		}); err != nil {
			return nil, fmt.Errorf("snapshot derived tree %q: %w", root, err)
		}
	}
	return snapshot, nil
}

func newDerivedRegenerationFixture(t *testing.T) string {
	t.Helper()

	sourceRoot := filepath.Clean(filepath.Join("..", ".."))
	fixtureRoot := t.TempDir()
	for _, directory := range []string{".agents", "docs/workflow/authorizations", "internal", "skills"} {
		if err := os.CopyFS(
			filepath.Join(fixtureRoot, directory),
			os.DirFS(filepath.Join(sourceRoot, directory)),
		); err != nil {
			t.Fatalf("copy regeneration fixture directory %s: %v", directory, err)
		}
	}
	for _, fileName := range []string{"Makefile", "go.mod", "go.sum", "skills-lock.json"} {
		sourcePath := filepath.Join(sourceRoot, fileName)
		content, err := os.ReadFile(sourcePath)
		if err != nil {
			t.Fatalf("read regeneration fixture file %s: %v", fileName, err)
		}
		info, err := os.Stat(sourcePath)
		if err != nil {
			t.Fatalf("stat regeneration fixture file %s: %v", fileName, err)
		}
		if err := os.WriteFile(filepath.Join(fixtureRoot, fileName), content, info.Mode().Perm()); err != nil {
			t.Fatalf("copy regeneration fixture file %s: %v", fileName, err)
		}
	}
	return fixtureRoot
}

func derivedArtifactsByRecord(
	t *testing.T,
	fileSystem fs.FS,
	roots []string,
	records map[string]derivedOwnershipRecord,
	resolved map[string]derivedOwnershipRecord,
) map[string][]string {
	t.Helper()

	artifacts := make(map[string][]string)
	exceptionClaims, err := derivedOwnershipExceptionClaims(records)
	if err != nil {
		t.Fatal(err)
	}
	for artifactPath := range resolved {
		info, err := fs.Stat(fileSystem, artifactPath)
		if err != nil {
			t.Fatalf("stat resolved derived path %q: %v", artifactPath, err)
		}
		if !info.Mode().IsRegular() {
			continue
		}
		var recordPaths []string
		for _, root := range roots {
			if !pathWithinDerivedScanRoot(artifactPath, root) {
				continue
			}
			recordPaths, err = resolveDerivedOwnershipRecordPaths(
				fileSystem, root, artifactPath, false,
			)
			if err != nil {
				t.Fatalf("resolve ownership for %q: %v", artifactPath, err)
			}
			break
		}
		if len(recordPaths) != 1 {
			t.Fatalf("resolved artifact %q has ownership records %v", artifactPath, recordPaths)
		}
		recordPath, _, _, err := resolveDerivedOwnershipRecord(
			records,
			exceptionClaims,
			recordPaths[0],
			artifactPath,
		)
		if err != nil {
			t.Fatalf("resolve ownership record for %q: %v", artifactPath, err)
		}
		artifacts[recordPath] = append(artifacts[recordPath], artifactPath)
	}
	for recordPath := range artifacts {
		sort.Strings(artifacts[recordPath])
	}
	return artifacts
}

func derivedRecordPathForArtifact(
	t *testing.T,
	fileSystem fs.FS,
	roots []string,
	records map[string]derivedOwnershipRecord,
	resolved map[string]derivedOwnershipRecord,
	artifactPath string,
) string {
	t.Helper()

	if _, ok := resolved[artifactPath]; !ok {
		t.Fatalf("changed derived artifact %q has no resolved ownership", artifactPath)
	}
	exceptionClaims, err := derivedOwnershipExceptionClaims(records)
	if err != nil {
		t.Fatal(err)
	}
	for _, root := range roots {
		if !pathWithinDerivedScanRoot(artifactPath, root) {
			continue
		}
		recordPaths, err := resolveDerivedOwnershipRecordPaths(
			fileSystem, root, artifactPath, false,
		)
		if err != nil {
			t.Fatalf("resolve ownership for changed artifact %q: %v", artifactPath, err)
		}
		if len(recordPaths) != 1 {
			t.Fatalf("changed artifact %q has ownership records %v", artifactPath, recordPaths)
		}
		recordPath, _, _, err := resolveDerivedOwnershipRecord(
			records,
			exceptionClaims,
			recordPaths[0],
			artifactPath,
		)
		if err != nil {
			t.Fatalf("resolve ownership record for changed artifact %q: %v", artifactPath, err)
		}
		return recordPath
	}
	t.Fatalf("changed derived artifact %q is outside the derived scan", artifactPath)
	return ""
}

func declaredSanctionedProbes(
	t *testing.T,
	fileSystem fs.FS,
	roots []string,
	records map[string]derivedOwnershipRecord,
	resolved map[string]derivedOwnershipRecord,
) []derivedArtifactProbe {
	t.Helper()

	probes := map[string]derivedArtifactProbe{
		"assets/setups/_ownership.yml": {
			path: "assets/setups/go-cli.json", owner: "sanctioned",
		},
		"assets/source-baselines/_ownership.yml": {
			path:  "assets/source-baselines/baseline.standard-typescript-monorepo-0.0.1/manifest.json",
			owner: "sanctioned",
		},
		"assets/formatter-fixtures/_ownership.yml": {
			path:  "assets/formatter-fixtures/standard-typescript-monorepo/golden/AGENTS.md",
			owner: "sanctioned",
		},
		"assets/profiles/_ownership.yml": {
			path:  "assets/profiles/standard-typescript-monorepo.json",
			owner: "sanctioned", perturb: perturbFormatterGoldenDigest,
		},
		"testdata/_ownership.yml": {
			path: "testdata/catalog.digest", owner: "sanctioned",
		},
		"testdata/catalog.diagnostics.golden.json_ownership.yml": {
			path: "testdata/catalog.diagnostics.golden.json", owner: "sanctioned",
		},
		"testdata/parity-corpus/_ownership.yml#v1/manifest.json": {
			path: "testdata/parity-corpus/v1/manifest.json", owner: "sanctioned",
		},
		"testdata/parity-corpus/_ownership.yml#v1/fixtures/asset-sync.json": {
			path: "testdata/parity-corpus/v1/fixtures/asset-sync.json", owner: "sanctioned",
		},
		"testdata/plan-characterization/_ownership.yml": {
			path: "testdata/plan-characterization/clean-adoption.golden.json", owner: "sanctioned",
		},
	}
	return probesForDeclaredOwner(
		t, fileSystem, roots, records, resolved, derivedOwnerSanctioned, probes,
	)
}

func declaredFrozenProbes(
	t *testing.T,
	fileSystem fs.FS,
	roots []string,
	records map[string]derivedOwnershipRecord,
	resolved map[string]derivedOwnershipRecord,
) []derivedArtifactProbe {
	t.Helper()

	probes := map[string]derivedArtifactProbe{
		"testdata/legacy-v2/_ownership.yml": {
			path: "testdata/legacy-v2/assets/coverage.json", owner: "frozen",
		},
		"testdata/adr-lifecycle/_ownership.yml": {
			path: "testdata/adr-lifecycle/accepted.md", owner: "frozen",
		},
		"testdata/parity-corpus/_ownership.yml": {
			path: "testdata/parity-corpus/v1/matrix.json", owner: "frozen",
		},
	}
	return probesForDeclaredOwner(
		t, fileSystem, roots, records, resolved, derivedOwnerFrozen, probes,
	)
}

func probesForDeclaredOwner(
	t *testing.T,
	fileSystem fs.FS,
	roots []string,
	records map[string]derivedOwnershipRecord,
	resolved map[string]derivedOwnershipRecord,
	owner derivedOwnershipOwner,
	probes map[string]derivedArtifactProbe,
) []derivedArtifactProbe {
	t.Helper()

	declarations := make(map[string]string)
	for recordPath, record := range records {
		if record.Owner == owner {
			declarations[recordPath] = recordPath
		}
		for _, exception := range record.Exceptions {
			if exception.Owner != owner {
				continue
			}
			declarationKey := recordPath + "#" + exception.Path
			declarations[declarationKey] = recordPath
		}
	}

	keys := make([]string, 0, len(declarations))
	for declarationKey, recordPath := range declarations {
		probe, ok := probes[declarationKey]
		if !ok {
			t.Fatalf("%s ownership declaration %q has no regeneration probe", owner, declarationKey)
		}
		resolvedRecord, ok := resolved[probe.path]
		if !ok {
			t.Fatalf("%s regeneration probe %q has no resolved ownership", owner, probe.path)
		}
		if resolvedRecord.Owner != owner {
			t.Fatalf("%s regeneration probe %q resolves to owner %q", owner, probe.path, resolvedRecord.Owner)
		}
		if got := derivedRecordPathForArtifact(t, fileSystem, roots, records, resolved, probe.path); got != recordPath {
			t.Fatalf("%s regeneration probe %q resolves through record %q, want %q", owner, probe.path, got, recordPath)
		}
		if separator := strings.IndexByte(declarationKey, '#'); separator >= 0 {
			exceptionPath, err := derivedOwnershipExceptionPath(
				recordPath,
				declarationKey[separator+1:],
			)
			if err != nil {
				t.Fatal(err)
			}
			if probe.path != exceptionPath {
				t.Fatalf("%s exception probe path = %q, want %q", owner, probe.path, exceptionPath)
			}
		}
		keys = append(keys, declarationKey)
	}
	if len(declarations) != len(probes) {
		t.Fatalf("%s regeneration probes = %d, ownership declarations = %d", owner, len(probes), len(declarations))
	}
	sort.Strings(keys)
	result := make([]derivedArtifactProbe, 0, len(keys))
	for _, declarationKey := range keys {
		result = append(result, probes[declarationKey])
	}
	return result
}

func filterDerivedArtifactsByOwner(
	artifactPaths []string,
	resolved map[string]derivedOwnershipRecord,
	owner derivedOwnershipOwner,
) []string {
	filtered := make([]string, 0, len(artifactPaths))
	for _, artifactPath := range artifactPaths {
		if resolved[artifactPath].Owner == owner {
			filtered = append(filtered, artifactPath)
		}
	}
	return filtered
}

func probesForPaths(paths []string, owner string) []derivedArtifactProbe {
	probes := make([]derivedArtifactProbe, 0, len(paths))
	for _, artifactPath := range paths {
		probes = append(probes, derivedArtifactProbe{path: artifactPath, owner: owner})
	}
	return probes
}

func cloneDerivedProbes(probes []derivedArtifactProbe) []derivedArtifactProbe {
	return append([]derivedArtifactProbe(nil), probes...)
}

func exerciseDeclaredRegenerationStep(
	ctx context.Context,
	repository string,
	baselineRoot string,
	cacheRoot string,
	roots []string,
	restoreTo map[string]derivedArtifactSnapshot,
	command string,
	rewrite []derivedArtifactProbe,
	untouched []derivedArtifactProbe,
) (resultErr error) {
	before, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	defer func() {
		if err := restoreDerivedTree(baselineRoot, roots, restoreTo); resultErr == nil && err != nil {
			resultErr = err
		}
	}()

	allProbes := append(cloneDerivedProbes(rewrite), untouched...)
	if err := perturbDerivedArtifacts(baselineRoot, before, allProbes); err != nil {
		return err
	}
	perturbed, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	if err := runDeclaredRegenerationStep(ctx, repository, cacheRoot, command); err != nil {
		return err
	}
	after, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	for _, probe := range rewrite {
		got, ok := after[probe.path]
		if !ok {
			return fmt.Errorf("declared command %q removed claimed artifact %q", command, probe.path)
		}
		if bytes.Equal(got.content, perturbed[probe.path].content) {
			return fmt.Errorf(
				"declared command %q left artifact %q unchanged after deliberate perturbation",
				command, probe.path,
			)
		}
		if !reflect.DeepEqual(got, before[probe.path]) {
			return fmt.Errorf(
				"declared command %q did not restore claimed artifact %q: %s",
				command,
				probe.path,
				firstDerivedContentDifference(before[probe.path].content, got.content),
			)
		}
	}
	for _, probe := range untouched {
		if !reflect.DeepEqual(after[probe.path], perturbed[probe.path]) {
			return fmt.Errorf(
				"declared command %q rewrote %s artifact %q outside its ownership",
				command, probe.owner, probe.path,
			)
		}
	}
	expected := cloneDerivedSnapshot(before)
	for _, probe := range untouched {
		expected[probe.path] = perturbed[probe.path]
	}
	if !reflect.DeepEqual(after, expected) {
		return fmt.Errorf("declared command %q changed artifacts outside its declared ownership", command)
	}
	return nil
}

// ambientGoBuildCache resolves the build cache the suite itself compiles
// with, so a declared regeneration command reuses warm build artifacts
// instead of recompiling the module from an empty cache. The declared
// contract these tests prove is byte-identical regeneration output, not a
// cold compile. Result caching stays content-governed: Go tracks the files a
// cached test read, so a perturbed artifact forces re-execution, an -update
// step never caches, and only a checking step over identical bytes may
// legitimately replay its verdict.
func ambientGoBuildCache(t *testing.T) string {
	t.Helper()
	ambientGoCacheOnce.Do(func() {
		if dir := strings.TrimSpace(os.Getenv("GOCACHE")); dir != "" {
			ambientGoCacheDir = dir
			return
		}
		output, err := exec.Command("go", "env", "GOCACHE").Output()
		if err != nil {
			ambientGoCacheErr = fmt.Errorf("resolve ambient go build cache: %w", err)
			return
		}
		ambientGoCacheDir = strings.TrimSpace(string(output))
	})
	if ambientGoCacheErr != nil {
		t.Fatal(ambientGoCacheErr)
	}
	if ambientGoCacheDir == "" {
		t.Fatal("resolve ambient go build cache: empty path")
	}
	return ambientGoCacheDir
}

var (
	ambientGoCacheOnce sync.Once
	ambientGoCacheDir  string
	ambientGoCacheErr  error
)

func runDeclaredRegenerationStep(
	ctx context.Context,
	repository string,
	cacheRoot string,
	command string,
) error {
	_, err := runDeclaredRegenerationStepOutput(ctx, repository, cacheRoot, command)
	return err
}

func runDeclaredRegenerationStepOutput(
	ctx context.Context,
	repository string,
	cacheRoot string,
	command string,
) ([]byte, error) {
	cmd := exec.CommandContext(ctx, "sh", "-c", command)
	cmd.Dir = repository
	cmd.Env = append(os.Environ(), "GOCACHE="+cacheRoot, "GOFLAGS=-buildvcs=false")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return output, fmt.Errorf("run declared command %q: %w\n%s", command, err, output)
	}
	return output, nil
}

func perturbDerivedArtifacts(
	baselineRoot string,
	before map[string]derivedArtifactSnapshot,
	probes []derivedArtifactProbe,
) error {
	seen := make(map[string]struct{}, len(probes))
	for _, probe := range probes {
		if _, duplicate := seen[probe.path]; duplicate {
			return fmt.Errorf("artifact %q has more than one regeneration probe", probe.path)
		}
		seen[probe.path] = struct{}{}
		snapshot, ok := before[probe.path]
		if !ok {
			return fmt.Errorf("regeneration probe artifact %q is absent", probe.path)
		}
		perturb := probe.perturb
		if perturb == nil {
			perturb = appendHarmlessWhitespace
		}
		content, err := perturb(snapshot.content)
		if err != nil {
			return fmt.Errorf("perturb artifact %q: %w", probe.path, err)
		}
		if bytes.Equal(content, snapshot.content) {
			return fmt.Errorf("perturbation left artifact %q unchanged", probe.path)
		}
		if err := os.WriteFile(
			filepath.Join(baselineRoot, filepath.FromSlash(probe.path)),
			content,
			snapshot.mode,
		); err != nil {
			return fmt.Errorf("write perturbed artifact %q: %w", probe.path, err)
		}
	}
	return nil
}

func appendHarmlessWhitespace(content []byte) ([]byte, error) {
	return append(append([]byte(nil), content...), ' ', '\n'), nil
}

func firstDerivedContentDifference(want []byte, got []byte) string {
	limit := min(len(want), len(got))
	index := 0
	for index < limit && want[index] == got[index] {
		index++
	}
	contextEnd := min(index+80, limit)
	return fmt.Sprintf(
		"first byte %d, want length %d and %q, got length %d and %q",
		index,
		len(want),
		want[index:contextEnd],
		len(got),
		got[index:contextEnd],
	)
}

func perturbFormatterGoldenDigest(content []byte) ([]byte, error) {
	const prefix = `"goldenDigest": "`
	start := bytes.Index(content, []byte(prefix))
	if start == -1 {
		return nil, errors.New("goldenDigest field is absent")
	}
	start += len(prefix)
	endOffset := bytes.IndexByte(content[start:], '"')
	if endOffset <= 0 {
		return nil, errors.New("goldenDigest value is malformed")
	}
	result := append([]byte(nil), content...)
	replacement := byte('0')
	if bytes.Count(result[start:start+endOffset], []byte{'0'}) == endOffset {
		replacement = '1'
	}
	for index := start; index < start+endOffset; index++ {
		result[index] = replacement
	}
	return result, nil
}

func writeDedicatedCommandFixture(
	t *testing.T,
	baselineRoot string,
	recordPath string,
	command string,
) {
	t.Helper()

	content := "owner: dedicated\ncommand: >-\n  " +
		strings.ReplaceAll(command, "\n", "\n  ") +
		"\nreason: deliberately invalid declared-step fixture\n"
	if err := os.WriteFile(
		filepath.Join(baselineRoot, filepath.FromSlash(recordPath)),
		[]byte(content),
		0o644,
	); err != nil {
		t.Fatalf("write declared-step fixture %q: %v", recordPath, err)
	}
	writeDedicatedAuthorizationFixture(t, baselineRoot, filepath.Dir(recordPath), command)
}

func writeDedicatedAuthorizationFixture(t *testing.T, baselineRoot, artifactDirectory, command string) {
	t.Helper()

	var outputs []string
	root := filepath.Join(baselineRoot, filepath.FromSlash(artifactDirectory))
	err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || entry.Name() == "_ownership.yml" {
			return nil
		}
		relative, err := filepath.Rel(baselineRoot, filePath)
		if err != nil {
			return err
		}
		outputs = append(outputs, filepath.ToSlash(filepath.Join("internal", "baseline", relative)))
		return nil
	})
	if err != nil {
		t.Fatalf("enumerate dedicated authorization fixture outputs: %v", err)
	}
	sort.Strings(outputs)

	var authorization strings.Builder
	authorization.WriteString("# Dedicated regeneration fixture\n\n## Sanctioned regeneration\n\n```yaml\ncommand: >-\n  ")
	authorization.WriteString(strings.ReplaceAll(command, "\n", "\n  "))
	authorization.WriteString("\noutputs:\n")
	for _, output := range outputs {
		authorization.WriteString("  - ")
		authorization.WriteString(output)
		authorization.WriteByte('\n')
	}
	authorization.WriteString("```\n")
	repository := filepath.Dir(filepath.Dir(baselineRoot))
	filePath := filepath.Join(repository, "docs", "workflow", "authorizations", "dedicated-fixture.md")
	if err := os.WriteFile(filePath, []byte(authorization.String()), 0o644); err != nil {
		t.Fatalf("write dedicated authorization fixture: %v", err)
	}
}

func restoreDerivedTree(
	baselineRoot string,
	roots []string,
	snapshot map[string]derivedArtifactSnapshot,
) error {
	current, err := readDerivedTreeSnapshot(baselineRoot, roots)
	if err != nil {
		return err
	}
	for artifactPath := range current {
		if _, existed := snapshot[artifactPath]; existed {
			continue
		}
		if err := os.Remove(filepath.Join(baselineRoot, filepath.FromSlash(artifactPath))); err != nil {
			return fmt.Errorf("remove generated fixture artifact %q: %w", artifactPath, err)
		}
	}
	paths := make([]string, 0, len(snapshot))
	for artifactPath := range snapshot {
		paths = append(paths, artifactPath)
	}
	sort.Strings(paths)
	for _, artifactPath := range paths {
		artifact := snapshot[artifactPath]
		fullPath := filepath.Join(baselineRoot, filepath.FromSlash(artifactPath))
		if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
			return fmt.Errorf("restore fixture directory for %q: %w", artifactPath, err)
		}
		if err := os.WriteFile(fullPath, artifact.content, artifact.mode); err != nil {
			return fmt.Errorf("restore fixture artifact %q: %w", artifactPath, err)
		}
	}
	return nil
}

func cloneDerivedSnapshot(
	snapshot map[string]derivedArtifactSnapshot,
) map[string]derivedArtifactSnapshot {
	clone := make(map[string]derivedArtifactSnapshot, len(snapshot))
	for artifactPath, artifact := range snapshot {
		clone[artifactPath] = artifact
	}
	return clone
}

func assertDerivedFixtureRestored(
	t *testing.T,
	baselineRoot string,
	roots []string,
	want map[string]derivedArtifactSnapshot,
) {
	t.Helper()

	got := snapshotDerivedTreeAt(t, baselineRoot, roots)
	if !reflect.DeepEqual(got, want) {
		t.Fatal("declared-step test did not restore the derived fixture")
	}
}
